[project]
name = "class-pro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chainlit>=2.5.5",
    "fastapi[standard]>=0.115.12",
    "openai-agents[viz]>=0.0.13",
    "tavily-python>=0.7.2",
]
